version: "3"

services:
  mongo:
    container_name: survey-database
    image: mongo:4.4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: survey-backend
    build: .
    image: node:16
    working_dir: /app
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/survey
    command: bash -c "npm install --omit=dev && npm run debug"
    volumes:
      - ./dist/:/app/dist/
      - ./package.json:/app/package.json
    ports:
      - "5000:5000"
      - "9222:9222"
    links:
      - mongo
